# 数据验证

In [1]:
#导包
import pandas as pd
from sqlalchemy import create_engine

In [21]:
#连接腾讯云
engine = create_engine('mysql+pymysql://root:lzx13695250408@gz-cdb-8bco4w6f.sql.tencentcdb.com:24347/use01?charset=utf8mb4')

In [39]:
#读取crude_daily表的数据
df_crude_daily = pd.read_sql('select * from futures_daily',engine)

date             0
open             0
high             0
low              0
close            0
volume           0
open_interest    0
动态结算价            0
dtype: int64

In [40]:
#检查空值
print('🩺 1. 检查是否有空值（NaN）：')
df_crude_daily.isnull().sum()

🩺 1. 检查是否有空值（NaN）：

date             0
open             0
high             0
low              0
close            0
volume           0
open_interest    0
动态结算价            0
dtype: int64

In [22]:
#导出数据
df_futures_daily = pd.read_sql('select * from futures_daily',engine)
df_futures_daily

,date,open,high,low,close,volume,open_interest,动态结算价
0,2025-01-02,3305.0,3335.0,3284.0,3306.0,1373928.0,1551112.0,3311.0
1,2025-01-03,3305.0,3309.0,3260.0,3272.0,1560003.0,1675464.0,3280.0
2,2025-01-06,3264.0,3287.0,3251.0,3252.0,1614675.0,1746201.0,3266.0
3,2025-01-07,3269.0,3278.0,3232.0,3239.0,1312041.0,1772105.0,3248.0
4,2025-01-08,3239.0,3250.0,3204.0,3211.0,1273140.0,1842567.0,3226.0
...,...,...,...,...,...,...,...,...
399,2026-08-26,3071.0,3080.0,3057.0,3076.0,725416.0,1386273.0,3070.0
400,2026-08-27,3071.0,3090.0,3071.0,3088.0,650663.0,1254003.0,3080.0
401,2026-08-28,3081.0,3129.0,3081.0,3112.0,862248.0,1100758.0,3109.0
402,2026-08-31,3160.0,3203.0,3159.0,3197.0,684968.0,1225097.0,3186.0
403,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#检查空值
print('🩺 1. 检查是否有空值（NaN）：')
df_futures_daily.isnull().sum()

🩺 1. 检查是否有空值（NaN）：

date             1
open             1
high             1
low              1
close            1
volume           1
open_interest    1
动态结算价            1
dtype: int64

In [29]:
#找出空值的行
bad_rows = df_futures_daily[df_futures_daily.isnull().any(axis=1)]
print(f'发现坏数据:\n {bad_rows}')

发现坏数据:
     date  open  high  low  close  volume  open_interest  动态结算价
403  NaT   NaN   NaN  NaN    NaN     NaN            NaN    NaN

In [32]:
#清洗
df_futures_daily.dropna(inplace=True)
#重新索引
df_futures_daily.reset_index(drop=True, inplace=True)
print('🩺 2. 检查清洗后的数据：')
df

🩺 2. 检查清洗后的数据：

,date,open,high,low,close,volume,open_interest,动态结算价
0,2025-01-02,3305.0,3335.0,3284.0,3306.0,1373928.0,1551112.0,3311.0
1,2025-01-03,3305.0,3309.0,3260.0,3272.0,1560003.0,1675464.0,3280.0
2,2025-01-06,3264.0,3287.0,3251.0,3252.0,1614675.0,1746201.0,3266.0
3,2025-01-07,3269.0,3278.0,3232.0,3239.0,1312041.0,1772105.0,3248.0
4,2025-01-08,3239.0,3250.0,3204.0,3211.0,1273140.0,1842567.0,3226.0
...,...,...,...,...,...,...,...,...
398,2026-08-25,3066.0,3079.0,3062.0,3071.0,651622.0,1501202.0,3070.0
399,2026-08-26,3071.0,3080.0,3057.0,3076.0,725416.0,1386273.0,3070.0
400,2026-08-27,3071.0,3090.0,3071.0,3088.0,650663.0,1254003.0,3080.0
401,2026-08-28,3081.0,3129.0,3081.0,3112.0,862248.0,1100758.0,3109.0
402,2026-08-31,3160.0,3203.0,3159.0,3197.0,684968.0,1225097.0,3186.0

In [33]:
#再看看有没有空值
print('🩺 3. 检查是否有空值（NaN）：')
df_futures_daily.isnull().sum()

🩺 3. 检查是否有空值（NaN）：

date             0
open             0
high             0
low              0
close            0
volume           0
open_interest    0
动态结算价            0
dtype: int64

In [37]:
#把数据写回去腾讯云数据库
df_futures_daily.to_sql('futures_daily', engine, if_exists='replace', index=False)
print('✅ 数据已写入腾讯云数据库')

✅ 数据已写入腾讯云数据库

## OHLC校验

In [35]:
"""
在金融数据中，有一条不可违背的“铁律”：
最高价（High）必须 ≥ 收盘价（Close），最低价（Low）必须 ≤ 收盘价（Close）。
如果数据源出错（比如列错位、传输错误），就会出现“收盘价比最高价还高”这种违反物理规律的情况。如果不检查出来，回测时你的策略可能会以为买在了最低点，实际上根本买不到。
"""
#1.找出逻辑错误的行
#条件：最高价 < 收盘价 OR 最低价 > 收盘价
logic_errors = df [(df['high'] < df['close']) |
    (df['low'] > df['close'])]
print(f"🕵️‍♂️ 发现 {len(logic_errors)} 条逻辑错误数据")

🕵️‍♂️ 发现 0 条逻辑错误数据

# 时间连续性检查

In [36]:
"""
金融数据最怕“断档”。如果中间少了一天（比如爬虫那天挂了没抓到），你在做回测时，策略会以为那是连续的交易日，导致计算均线或收益率时出现“未来函数”或者巨大的跳空缺口。
我们需要确认：
日期是否连续？（排除周末和节假日后，中间有没有漏掉工作日）
有没有重复的日期？（防止同一天有两条数据）
"""
# 1. 检查是否有重复日期
dup_dates = df[df.duplicated(subset=['date'])]
print(f"🕵️‍♂️ 1. 重复日期检查：发现 {len(dup_dates)} 条重复记录")

# 2. 检查时间跨度
min_date = df['date'].min()
max_date = df['date'].max()
total_days = (max_date - min_date).days
print(f"\n📅 2. 时间跨度：从 {min_date} 到 {max_date}，共 {total_days} 天")
print(f"📊 3. 实际数据行数：{len(df)} 行")

# 3. 简单判断缺失率（粗略估算）
# 假设一年约 240-250 个交易日
expected_rows = total_days * 0.68  # 0.68 是去除周末的大致比例
print(f"\n💡 预期行数（粗略）：约 {int(expected_rows)} 行")
if len(df) < expected_rows * 0.9:
    print("⚠️ 警告：实际行数明显少于预期，可能存在大量缺失！")
else:
    print("✅ 数据密度看起来是正常的。")

🕵️‍♂️ 1. 重复日期检查：发现 0 条重复记录

📅 2. 时间跨度：从 2025-01-02 00:00:00 到 2026-08-31 00:00:00，共 606 天
📊 3. 实际数据行数：403 行

💡 预期行数（粗略）：约 412 行
✅ 数据密度看起来是正常的。